language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=1.8
  - NUMPY_VERSION=1.7
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy=$NUMPY_VERSION scipy matplotlib
  - source activate env_name
  - pip install -r requirements.txt
  - pip install .
script:
  - python tests/all_tests.py --emperor_scripts_dir scripts
