language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=1.8
  - NUMPY_VERSION=1.7
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy=$NUMPY_VERSION scipy matplotlib openpyxl=1.8.2 pandas
  - source activate env_name
  - pip install sphinx sphinx-bootstrap-theme future==0.13
  - pip install -e .
script:
  - python tests/all_tests.py --emperor_scripts_dir scripts
  - make -C doc html
